apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chirpstack-network-server
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: chirpstack-network-server
  template:
    metadata:
      labels:
        app: chirpstack-network-server
    spec:
      containers:
        - name: chirpstack-network-server
          image: chirpstack/chirpstack-network-server:3.10.0
          env:
            - name: POSTGRESQL__DSN
              valueFrom:
                secretKeyRef:
                  name: chirpstack-network-server-secrets
                  key: postgresql_dsn
            - name: REDIS__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chirpstack-network-server-secrets
                  key: redis_password
            - name: NETWORK_SERVER__GATEWAY__BACKEND__MQTT__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chirpstack-network-server-secrets
                  key: mqtt_password
            - name: NETWORK_SERVER__GATEWAY__BACKEND__MQTT__CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: tcp
              containerPort: 8000
            - name: monitoring-port
              containerPort: 8004
          resources:
            limits:
              cpu: "3"
              memory: 1500Mi
            requests:
              cpu: "2"
              memory: 1000Mi
          volumeMounts:
            - name: chirpstack-network-server
              mountPath: /etc/chirpstack-network-server/chirpstack-network-server.toml
              subPath: chirpstack-network-server.toml
      volumes:
        - name: chirpstack-network-server
          configMap:
            name: chirpstack-network-server
